// Run against the actual Go-rendered page. See admin-ui-validation.md.
const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { JSDOM } = require('jsdom');
const renderDir = process.env.SPORTS_UI_RENDER_DIR;
if (!renderDir)
  throw new Error(
    'Set SPORTS_UI_RENDER_DIR to the directory generated by TestSportsAdminTemplateRendersBothScopes',
  );
const settle = async () => {
  for (let i = 0; i < 5; i++) await new Promise((resolve) => setImmediate(resolve));
};
const empty = () => ({
  version: 1,
  pinnedSportIds: [],
  competitionIds: [],
  teamIds: [],
  athleteIds: ['preserve-athlete'],
  schools: [],
});
async function setup(master = true, override) {
  const html = fs.readFileSync(
    path.join(renderDir, master ? 'sports-admin.html' : 'sports-account.html'),
    'utf8',
  );
  const dom = new JSDOM(html, { url: 'http://localhost/prefix/account/sports', runScripts: 'outside-only' });
  const calls = [];
  dom.window.confirm = () => true;
  dom.window.fetch = async (url, options = {}) => {
    const body = options.body ? JSON.parse(options.body) : undefined;
    calls.push({ url, method: options.method, body });
    if (override) {
      const result = override(url, options, body);
      if (result) return result;
    }
    let data;
    if (url.endsWith('/catalog'))
      data = {
        leagues: [
          { id: 'nfl', name: 'NFL', sport: 'football', enabled: true, supportsTeams: true },
          { id: 'soccer-eng.1', name: 'Premier League', sport: 'soccer', enabled: false, supportsTeams: true },
        ],
      };
    else if (url.includes('/catalog?teams=1'))
      data = {
        teams: [
          { id: 'nfl:1', name: 'Falcons', league: 'nfl' },
          { id: 'nfl:2', name: 'Bills', league: 'nfl' },
        ],
        partial: false,
      };
    else if (url.endsWith('/settings'))
      data = body || {
        enabledLeagues: ['nfl'],
        defaultSourceIds: ['keep-source'],
        favoriteTeamIds: [],
        defaultCategoryIds: [],
        leagueSearchOverrides: { nfl: { sourceIds: ['keep-override'] } },
      };
    else data = body ? { ...body, revision: body.revision + 1 } : { revision: 4, preferences: empty() };
    return { ok: true, json: async () => JSON.parse(JSON.stringify(data)) };
  };
  const script = [...dom.window.document.scripts].find((script) =>
    script.textContent.includes('const followIDs ='),
  );
  assert.ok(script, 'sports editor script is rendered');
  dom.window.eval(script.textContent);
  await settle();
  const get = (id) => dom.window.document.getElementById('sports-' + id);
  return { dom, calls, get };
}
test('profile saves preserve unedited preferences, use app IDs, and keep searched-away teams', async () => {
  const { dom, calls, get } = await setup(false);
  try {
    get('pins').querySelector('[value="soccer"]').click();
    get('follows').querySelector('[value="premier-league"]').click();
    get('teams').querySelector('[value="nfl:1"]').click();
    get('team-search').value = 'Bills';
    get('team-search').dispatchEvent(new dom.window.Event('input'));
    get('teams').querySelector('[value="nfl:2"]').click();
    get('save-profile').click();
    await settle();
    const saved = calls.find((call) => call.method === 'PUT').body;
    assert.equal(saved.revision, 4);
    assert.deepEqual(saved.preferences.pinnedSportIds, ['soccer']);
    assert.deepEqual(saved.preferences.competitionIds, ['premier-league']);
    assert.deepEqual(saved.preferences.teamIds, ['nfl:1', 'nfl:2']);
    assert.deepEqual(saved.preferences.athleteIds, ['preserve-athlete']);
    assert.match(get('profile-status').textContent, /Saved/);
    assert.equal(
      calls.some((call) => call.url.endsWith('/settings')),
      false,
    );
  } finally {
    dom.window.close();
  }
});
test('server saves preserve stream scopes and prevent an empty league list', async () => {
  const { dom, calls, get } = await setup();
  try {
    get('availability').querySelector('[value="nfl"]').click();
    get('save-server').click();
    await settle();
    assert.equal(calls.filter((call) => call.method === 'PUT').length, 0);
    assert.match(get('server-status').textContent, /at least one/);
    get('availability').querySelector('[value="soccer-eng.1"]').click();
    get('save-server').click();
    await settle();
    const saved = calls.find((call) => call.method === 'PUT').body;
    assert.deepEqual(saved.enabledLeagues, ['soccer-eng.1']);
    assert.deepEqual(saved.defaultSourceIds, ['keep-source']);
    assert.deepEqual(saved.leagueSearchOverrides, { nfl: { sourceIds: ['keep-override'] } });
  } finally {
    dom.window.close();
  }
});
test('a stale profile save requires reload before another write', async () => {
  const { dom, get } = await setup(false, (url, options) =>
    options.method === 'PUT' ? Promise.resolve({ ok: false, status: 409 }) : null,
  );
  try {
    get('pins').querySelector('[value="soccer"]').click();
    get('save-profile').click();
    await settle();
    assert.match(get('profile-status').textContent, /changed elsewhere/);
    assert.equal(get('save-profile').disabled, true);
    assert.equal(get('reload-profile').disabled, false);
    get('reload-profile').click();
    await settle();
    assert.equal(get('save-profile').disabled, false);
  } finally {
    dom.window.close();
  }
});
test('a late request for one profile cannot replace another profile draft', async () => {
  let resolveFirst;
  const { dom, get } = await setup(false, (url) =>
    url.endsWith('/profiles/one')
      ? new Promise((resolve) => {
          resolveFirst = resolve;
        })
      : null,
  );
  try {
    const option = dom.window.document.createElement('option');
    option.value = 'two';
    option.textContent = 'Sam';
    get('profile').append(option);
    get('profile').value = 'two';
    get('profile').dispatchEvent(new dom.window.Event('change'));
    await settle();
    resolveFirst({
      ok: true,
      json: async () => ({ revision: 4, preferences: { ...empty(), pinnedSportIds: ['soccer'] } }),
    });
    await settle();
    assert.equal(get('profile').value, 'two');
    assert.equal(get('pins').querySelector('[value="soccer"]').checked, false);
  } finally {
    dom.window.close();
  }
});
test('failed team fetch keeps stored favorites editable', async () => {
  const { dom, get } = await setup(false, (url) => {
    if (url.includes('/catalog?teams=1')) return Promise.reject(new Error('offline'));
    if (url.endsWith('/profiles/one'))
      return Promise.resolve({
        ok: true,
        json: async () => ({ revision: 2, preferences: { ...empty(), teamIds: ['nfl:99'] } }),
      });
  });
  try {
    assert.equal(get('teams').querySelector('[value="nfl:99"]').checked, true);
    assert.match(get('team-status').textContent, /Retry unavailable/);
    assert.equal(get('save-profile').disabled, false);
  } finally {
    dom.window.close();
  }
});

test('all catalog leagues and sports are selectable, including disabled team leagues', async () => {
  const {dom, get, calls} = await setup(false, (url) => {
    if (url.endsWith('/catalog')) return Promise.resolve({ok:true,json:async()=>({leagues:[
      {id:'wnba',name:'WNBA',sport:'basketball',enabled:false,supportsTeams:true},
      {id:'rugby-180659',name:'Six Nations',sport:'rugby',enabled:false,supportsTeams:true},
      {id:'ufc',name:'UFC',sport:'mma',enabled:true,supportsTeams:false}
    ]})});
    if(url.includes('teams=1')) return Promise.resolve({ok:true,json:async()=>({teams:[{id:'wnba:1',name:'Atlanta Dream',league:'wnba'}],partial:false})});
  });
  try {
    assert.ok(get('pins').querySelector('[value="rugby"]'));
    assert.ok(get('pins').querySelector('[value="mma"]'));
    assert.ok(get('follows').querySelector('[value="wnba"]'));
    assert.ok(get('follows').querySelector('[value="ufc"]'));
    assert.ok(get('teams').querySelector('[value="wnba:1"]'));
    assert.ok(calls.some(c=>c.url.endsWith('league=wnba')));
    assert.ok(!calls.some(c=>c.url.endsWith('league=ufc')));
    get('teams').querySelector('[value="wnba:1"]').click();
    get('filter').value='rugby';get('filter').dispatchEvent(new dom.window.Event('change'));
    assert.equal(get('teams').querySelector('[value="wnba:1"]'),null);
    get('save-profile').click();await settle();
    assert.deepEqual(calls.find(c=>c.method==='PUT').body.preferences.teamIds,['wnba:1']);
  } finally {dom.window.close();}
});
test('favorite types and selected-only filters preserve selections and summarize them', async () => {
  const {dom,get}=await setup(false);
  try {
    get('tab-teams').click();
    assert.equal(get('panel-teams').hidden,false);
    assert.equal(get('panel-leagues').hidden,true);
    get('teams').querySelector('[value="nfl:1"]').click();
    get('selected-only').click();
    assert.ok(get('teams').querySelector('[value="nfl:1"]'));
    assert.equal(get('teams').querySelector('[value="nfl:2"]'),null);
    assert.match(get('summary').textContent,/1 teams selected/);
  } finally {dom.window.close();}
});
test('sport selectors reflect partial selection and toggle every child even during search', async () => {
  const {dom,get,calls}=await setup(true,(url)=>url.endsWith('/catalog') ? Promise.resolve({ok:true,json:async()=>({leagues:[
    {id:'nfl',name:'NFL',sport:'football',enabled:true,supportsTeams:false},
    {id:'college-football',name:'NCAAF',sport:'football',enabled:false,supportsTeams:false},
    {id:'nba',name:'NBA',sport:'basketball',enabled:false,supportsTeams:false}
  ]})}) : null);
  try {
    const parent=()=>get('availability').querySelector('[data-sport-parent="football"]');
    assert.equal(parent().indeterminate,true);
    get('server-search').value='NFL';get('server-search').dispatchEvent(new dom.window.Event('input'));
    parent().click();
    assert.equal(parent().checked,true); assert.equal(parent().indeterminate,false);
    get('save-server').click();await settle();
    assert.deepEqual(calls.find(c=>c.method==='PUT').body.enabledLeagues,['nfl','college-football']);
    parent().click(); assert.equal(parent().checked,false);
    get('enable-all').click(); assert.match(get('availability-count').textContent,/3 of 3/);
    get('disable-all').click(); assert.match(get('availability-count').textContent,/0 of 3/);
    get('save-server').click();await settle();
    assert.equal(calls.filter(c=>c.method==='PUT').length,1);
    assert.match(get('server-status').textContent,/at least one/);
  } finally {dom.window.close();}
});
test('availability receives focus on opening and sports expand independently of selection', async () => {
  const {dom,get}=await setup(true);
  try {
    const section=get('server');
    let scrolled=false;section.scrollIntoView=()=>{scrolled=true;};
    section.open=true;section.dispatchEvent(new dom.window.Event('toggle'));
    assert.equal(dom.window.document.activeElement,section.querySelector('summary'));
    assert.equal(scrolled,true);
    const children=get('leagues-football');
    const toggle=get('availability').querySelector('[aria-controls="sports-leagues-football"]');
    assert.equal(children.hidden,true);
    toggle.click();assert.equal(children.hidden,false);assert.equal(toggle.getAttribute('aria-expanded'),'true');
    const parent=get('availability').querySelector('[data-sport-parent="football"]');
    parent.click();assert.equal(children.hidden,false);assert.equal(parent.checked,false);
    toggle.click();assert.equal(children.hidden,true);
    assert.ok(get('availability').querySelector('svg.sports-sport-icon[aria-hidden="true"]'));
    get('server-search').value='NFL';get('server-search').dispatchEvent(new dom.window.Event('input'));
    assert.equal(get('leagues-football').hidden,false);
  } finally {dom.window.close();}
});
test('sport header text expands without changing selection; checkbox does not collapse', async () => {
 const {dom,get}=await setup(true);
 try {
  const toggle=get('availability').querySelector('[aria-controls="sports-leagues-football"]');
  const input=get('availability').querySelector('[data-sport-parent="football"]');
  toggle.querySelector('.sports-sport-name').click();
  assert.equal(get('leagues-football').hidden,false);assert.equal(input.checked,true);
  input.click();assert.equal(input.checked,false);assert.equal(get('leagues-football').hidden,false);
  toggle.click();assert.equal(get('leagues-football').hidden,true);assert.equal(input.checked,false);
 } finally {dom.window.close();}
});

test('expanding a sport focuses its first league and brings the group into view', async () => {
 const {dom,get}=await setup(true);
 try {
  const group=get('leagues-football');let scrolled=false;
  group.closest('.sports-sport-group').scrollIntoView=()=>{scrolled=true;};
  const toggle=get('availability').querySelector('[aria-controls="sports-leagues-football"]');
  toggle.click();
  assert.equal(dom.window.document.activeElement,group.querySelector('input'));
  assert.equal(scrolled,true);
  assert.equal(group.querySelector('input').checked,true);
  scrolled=false;toggle.click();assert.equal(scrolled,false);
 } finally {dom.window.close();}
});
